[project]
name = "ifdo"
version = "1.5.0"
description = "Python iFDO implementation"
readme = "README.md"
authors = [
    {name = "Kevin Barnard", email = "kbarnard@mbari.org"},
    {name = "Chris Jackett", email = "chris.jackett@csiro.au"},
    {name = "Karsten Schimpf", email = "karsten.schimpf@awi.de"},
]
license = {text = "MIT"}
requires-python = ">=3.10"

dependencies = [
    "pyyaml<7.0,>=6.0",
    "pydantic<3.0.0,>=2.4.2",
]

[dependency-groups]
dev = [
    "pre-commit<5.0.0,>=4.0.1",
    "ruff<1.0.0,>=0.7.3",
    "black>=24.10.0,<27.0.0",
    "mypy>=1.13.0,<3.0.0",
    "bandit<2.0.0,>=1.7.10",
    "types-pyyaml<7.0.0.0,>=6.0.12.20240917",
    "pytest>=8.3.4,<10.0.0",
    "nox>=2025.2.9,<2027.0.0",
    "jsonschema<5.0.0,>=4.23.0"
]

[tool.uv]
package=true

[tool.setuptools.packages.find]
include = ["ifdo*"]

